# Generated by Django 2.2.14 on 2021-08-27 08:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adddress',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=0, max_length=100, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug '),
        ),
    ]
