# Generated by Django 2.2.14 on 2021-08-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210827_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='ProAddress',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='ProCountry',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='ProImage',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='join_date',
            new_name='ProJoin_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='slug',
            new_name='ProSlug',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='ProUser',
        ),
    ]
