# Generated by Django 2.2.14 on 2021-08-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210827_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProAddress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
    ]
