# Generated by Django 2.1.4 on 2021-09-25 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210925_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Client',
            new_name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Category', verbose_name='Category'),
        ),
    ]
