# Generated by Django 2.1.4 on 2021-09-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210925_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='projects/', verbose_name='Images'),
        ),
    ]
