# Generated by Django 2.1.4 on 2021-10-10 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20211010_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxnumpost',
            name='max_num',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
        migrations.AlterField(
            model_name='maxnumpost',
            name='user_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
