# Generated by Django 2.1.4 on 2021-10-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20211010_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxnumpost',
            name='max_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
