# Generated by Django 2.1.4 on 2021-10-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
