# Generated by Django 2.1.4 on 2021-10-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20211010_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxnumpost',
            name='max_num',
            field=models.IntegerField(blank=True, default='2', null=True),
        ),
    ]
