# Generated by Django 2.1.4 on 2021-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
