# Generated by Django 2.1.4 on 2021-10-08 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20211006_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visitor_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.CharField(default=datetime.datetime(2021, 10, 8, 9, 17, 12, 742985, tzinfo=utc), max_length=19),
        ),
    ]
