# Generated by Django 2.1.4 on 2021-10-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20211008_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.CharField(default='2021-10-08 09:50:02', max_length=19),
        ),
    ]
