# Generated by Django 2.1.4 on 2021-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20211008_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.CharField(default='2021-10-08  09:53:18', max_length=19),
        ),
    ]
