# Generated by Django 2.1.4 on 2021-10-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20211009_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date '),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='github  '),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_demo_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='live demo  '),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date '),
        ),
    ]
